import Head from "next/head";
import Link from "next/link";
import { FormEvent } from "react";

import { api } from "~/utils/api";

export default function Home() {
  const hello = api.post.hello.useQuery({ text: "from tRPC" });

  const handleSubmit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault()
    const data = new FormData(event.currentTarget)

    const name = data.get('name')
    const email = data.get('email')
    const problem = data.get('problem')

    console.log({name, email, problem})
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen">
        <div className="flex h-full">

            <div className="flex m-auto items-center gap-8">
              <form className="flex gap-4 flex-col" onSubmit={handleSubmit}>
                <div>
                  <label htmlFor="name"> Name </label>
                  <div>
                    <input name="name" placeholder="Carlos Lahrssen" />
                  </div>
                </div>

                <div>
                  <label htmlFor="email"> Email </label>
                  <div>
                    <input name="email" type="email" placeholder="carloslahrssen@gmail.com"/>
                  </div>  
                </div>

                <div> 
                  <label htmlFor="problem">Problem</label>
                  <p> Description goes here in lighter text </p>
                  <div>
                  <textarea id="problem" className="text-pretty"></textarea>  
                  </div>  
                </div>

                <div>
                  <button type="submit" className="bg-black p-3 text-white">
                    Submit Ticket
                  </button>
                </div>
              </form>
            </div>

        </div>
      </main>
    </>
  );
}
